Repository Geon-Owl/todo-list, pull requests merged in 2022-04, with the labels that each got.

#3 test: Git pull request issue test
  README.md
Labels: Owl, Test

#5 [Geon] Readme 작성
  README.md
Labels: Geon, Docs

#6 Revert "[Geon] Readme 작성"
  README.md
Labels: Geon, Docs

#7 [Geon][#1] Readme 재작성
  README.md
Labels: Geon, Docs

#13 [Owl][#12] Component class 구현
  src/core/Component.js
Labels: Owl, Feat

#15 [Geon][#14]Sass 환경설정
  babel.config.json
  package-lock.json
  package.json
  src/app.html
  src/scss/style.scss
Labels: Chore

#18 [#17]Feat: Header component 구현
  src/component/Header.js
  src/core/Component.js
  src/style/imgs/menuButton.png
  src/style/scss/Header.scss
Labels: Owl, Feat

#19 [Geon][#16] Column 컴포넌트 구현
  .gitignore
  package.json
  src/app.html
  src/app.js
  src/component/Header.js
  src/components/Column.js
  src/components/Header.js
  src/core/Component.js
  src/scss/style.scss
  src/style/images/delete.png
  src/style/images/menuButton.png
  src/style/images/plus.png
  src/style/scss/Column.scss
  src/style/scss/Header.scss
  src/style/scss/style.scss
Labels: Geon, Feat

#21 [Geon][#20]Chore: json server 설정
  data.json
  package-lock.json
  package.json
Labels: Geon, Chore

#25 [Geon] json-server fetch
  src/api.js
  src/app.js
Labels: Geon, Feat

#31 [Owl][#29] menu 추가 기능 구현
  src/app.js
  src/components/Header.js
  src/components/Menu.js
  src/style/scss/Menu.scss
Labels: Owl, Feat

#32 Card 추가 기능 구현중 리뷰를 위한 PR
  src/components/Cards.js
  src/components/Column.js
  src/style/scss/Cards.scss
Labels: Geon, Feat

#33 30-json-server-데이터-변경
  data.json
  src/api.js
  src/app.js
Labels: Geon, Owl, Refactor

#34 Card 추가 기능 완료
  src/api.js
  src/components/Cards.js
  src/components/Column.js
  src/style/images/plus-blue.png
  src/style/scss/Cards.scss
  src/style/scss/Column.scss
Labels: Geon, Feat

#36 29 menu 추가 기능 구현
  .vscode/settings.json
  data.json
  src/api.js
  src/app.js
  src/components/Cards.js
  src/components/Column.js
  src/components/Header.js
  src/components/History.js
  src/components/Menu.js
  src/style/scss/Header.scss
  src/style/scss/Menu.scss
  src/style/scss/style.scss
Labels: Owl, Feat, Style, Chore

#37 Card 삭제 기능 구현
  .vscode/settings.json
  data.json
  src/api.js
  src/components/Alert.js
  src/components/Cards.js
  src/style/scss/Alert.scss
  src/style/scss/style.scss
Labels: Geon, Feat

#39 [#29]Refactor: 자잘한 버그 수정 및 관련없는 함수 분리
  data.json
  src/api.js
  src/components/Cards.js
  src/components/History.js
Labels: Fix, Refactor
